version: '3.9'

services:
  server:
    build:
      context: ./server
      container_name: express-server
      #dockerfile: Dockerfile
    ports:
      - 4000:4000
    networks:
      - fullstack-net
    restart: unless-stopped
    #volumes:
    #  - ./server:/app
    #depends_on:
    #  - client


  client:
    build:
      context: ./client
      container_name: react-client
      #dockerfile: Dockerfile
    ports:
      - 5174:3000
    #volumes:
    #  - ./client:/app
    networks:
      - fullstack-net
    depends_on:
      - server
    restart: unless-stopped

networks:
  fullstack-net:
    driver: bridge